repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-format
  - repo: local
    hooks:
      - id: cspell
        name: cspell
        entry: bash -c 'git diff --cached --name-only | npm exec cspell -- --no-summary --no-progress --no-must-find-files --file-list stdin'
        language: system
        pass_filenames: false

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: check
        name: project checks
        entry: just check
        language: system
        pass_filenames: false
